### ISSUE TITLE
Missing meta data

### ISSUE THREAD

**Issue by sarigs** [chkp-sarigs/foo3#3]
Dear Developer, 
 For readability and Search Engine Optimization (SEO) it would be great if you could do the followings:
- [ ] Please provide more than 10 words in the "About" field
- [ ] Please provide relevant "Topics" 
> Recommended Topics: 
>**Environments**:
>azure, aws, gcp
>**Functionality**:
>build, deploy, staging, operate, terraform, ansible, helm, android, cloudguardIaaS, management, gaia, threat-prevention, identity-awareness, smp, iot, cloudguard-connect, cloudguard-dome9, malware, evasion
- [ ] Please provide README.md file with more than 150 chars
